"""update task table

Revision ID: 1f3ed5af8016
Revises: 62dbffe8a183
Create Date: 2023-09-30 20:11:37.901007

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f3ed5af8016'
down_revision = '62dbffe8a183'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('completed_by_user_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('fk_task_table_user_id_user_table', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_task_table_completed_by_user_id_user_table'), 'user_table', ['completed_by_user_id'], ['id'])
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_task_table_completed_by_user_id_user_table'), type_='foreignkey')
        batch_op.create_foreign_key('fk_task_table_user_id_user_table', 'user_table', ['user_id'], ['id'])
        batch_op.drop_column('completed_by_user_id')

    # ### end Alembic commands ###
