"""Update relationships

Revision ID: 62dbffe8a183
Revises: f9b32d5c3f52
Create Date: 2023-09-27 02:17:45.490073

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62dbffe8a183'
down_revision = 'f9b32d5c3f52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('family_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('family_name', sa.String(), nullable=False),
    sa.Column('family_username', sa.String(), nullable=True),
    sa.Column('_password_hash', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('family_username')
    )
    op.create_table('user_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('head_of_household', sa.Boolean(), nullable=False),
    sa.Column('family_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['family_id'], ['family_table.id'], name=op.f('fk_user_table_family_id_family_table')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.Column('frequency', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('family_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['family_id'], ['family_table.id'], name=op.f('fk_task_table_family_id_family_table')),
    sa.ForeignKeyConstraint(['user_id'], ['user_table.id'], name=op.f('fk_task_table_user_id_user_table')),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('tasks')
    op.drop_table('families')
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('head_of_household', sa.BOOLEAN(), nullable=False),
    sa.Column('family_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], name='fk_users_family_id_families'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('families',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('family_name', sa.VARCHAR(), nullable=False),
    sa.Column('family_username', sa.VARCHAR(), nullable=True),
    sa.Column('_password_hash', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('family_username')
    )
    op.create_table('tasks',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(), nullable=False),
    sa.Column('location', sa.VARCHAR(), nullable=True),
    sa.Column('description', sa.VARCHAR(), nullable=False),
    sa.Column('points', sa.INTEGER(), nullable=True),
    sa.Column('frequency', sa.VARCHAR(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('family_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], name='fk_tasks_family_id_families'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_tasks_user_id_users'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('task_table')
    op.drop_table('user_table')
    op.drop_table('family_table')
    # ### end Alembic commands ###
