"""Add User model with family relation

Revision ID: 8d9a979fc2f1
Revises: 941298cc07d6
Create Date: 2023-09-26 20:25:09.311822

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d9a979fc2f1'
down_revision = '941298cc07d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('head_of_household', sa.Boolean(), nullable=False),
    sa.Column('family_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], name=op.f('fk_users_family_id_families')),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('families', schema=None) as batch_op:
        batch_op.alter_column('family_name',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('families', schema=None) as batch_op:
        batch_op.alter_column('family_name',
               existing_type=sa.VARCHAR(),
               nullable=True)

    op.drop_table('users')
    # ### end Alembic commands ###
