"""Update family model

Revision ID: 941298cc07d6
Revises: 
Create Date: 2023-09-26 20:02:24.287041

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '941298cc07d6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('families',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('family_name', sa.String(), nullable=True),
    sa.Column('family_username', sa.String(), nullable=True),
    sa.Column('_password_hash', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('family_username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('families')
    # ### end Alembic commands ###
